Use the native 1password SSHKeys type to store & retrieve ssh keys

diff --git a/dotfiles/dot_bash.d/1password b/dotfiles/dot_bash.d/1password
--- a/dotfiles/dot_bash.d/1password
+++ b/dotfiles/dot_bash.d/1password
@@ -71,28 +71,32 @@ function openv() {
       export SSH_AUTH_SOCK
       export SSH_AGENT_PID
     fi
+    ssh-add -D
 
-    local data
-    data=`op item get --format=json --vault="Private" "dotfiles-secrets-ssh-config"`
-
+    local keylist
+    keylist=`op item list --categories SSHKey --format=json --vault="Private"`
     if [ "$?" -ne 0 ]; then
-      echo "Failed to get retrieve SSH keys"
+      echo "Failed to get retrieve SSH key list"
       return 1
     fi
 
-    for section in $(echo ${data} | jq -r -c '.sections[] | @base64'); do
+    for sshkey in $(echo ${keylist} | jq -r -c '.[] | @base64'); do
       _val() {
-        echo ${section} | base64 --decode | jq -r ${1}
+        echo ${sshkey} | base64 --decode | jq -r ${1}
       }
-      _title=$(_val '.label')
       _id=$(_val '.id')
 
-      _privatekey=$(echo ${data} | jq --arg SECTIONID "$_id" -r '.fields[] | select(.label == "private" and .section.id == $SECTIONID) | .value')
-      _publickey=$(echo ${data} | jq --arg SECTIONID "$_id" -r '.fields[] | select(.label == "public" and .section.id == $SECTIONID) | .value')
+      local data
+      data=`op item get --format=json "${_id}"`
+      if [ "$?" -ne 0 ]; then
+        echo "Failed to get retrieve SSH key"
+        return 1
+      fi
 
-      _fp=$(echo -ne "${_publickey}" | ssh-keygen -lf -)
-      echo "Adding key: ${_title} - ${_fp}"
-      echo -ne "${_privatekey}" | ssh-add -
+      _fingerprint=$(echo "${data}" | jq -r '.fields[] | select(.id == "fingerprint") | .value')
+      _privatekey=$(echo "${data}" | jq -r '.fields[] | select(.id == "private_key") | .value')
+      echo "Adding key: ${_fingerprint}"
+      echo "${_privatekey}" | ssh-add -
     done
   fi
 }
