Fix warnings & get rid of extraneous output

diff --git a/dotfiles/dot_bash.d/1password b/dotfiles/dot_bash.d/1password
--- a/dotfiles/dot_bash.d/1password
+++ b/dotfiles/dot_bash.d/1password
@@ -25,7 +25,8 @@ function openv() {
       local op_email
       read op_email
 
-      local token=$(op account add --address my.1password.ca --email "$op_email" --signin --raw)
+      local token
+      token=`op account add --address my.1password.ca --email "$op_email" --signin --raw`
       echo "$token" > "$openv_sess_file"
 
       export OP_SESSION_my="$token"
@@ -35,7 +36,11 @@ function openv() {
     local token
     { IFS= read -r token; } < "$openv_sess_file"
     export OP_CONFIG_DIR="$openv_config_dir"
-    token=$(op signin --account my.1password.ca --raw --session "$token")
+    token=`op signin --account my.1password.ca --raw --session "$token" 2>/dev/null`
+    if [ "$?" -ne 0 ]; then
+      echo "Unable to sign in to 1password account"
+      return 1
+    fi
     echo "$token" > "$openv_sess_file"
     export OP_SESSION_my="$token"
   fi
@@ -45,7 +50,10 @@ function openv() {
       local token
       { IFS= read -r token; } < "$openv_sess_file"
       export OP_CONFIG_DIR="$openv_config_dir"
-      op signout --account my.1password.ca --session "$token" --forget
+      op signout --account my.1password.ca --session "$token" --forget 2>/dev/null
+      if [ "$?" -ne 0 ]; then
+        echo "Unable to sign out of 1password account"
+      fi
     fi
 
     rm -rf "${openv_config_dir}/config"
@@ -74,7 +82,7 @@ function openv() {
     ssh-add -D
 
     local keylist
-    keylist=`op item list --categories SSHKey --format=json --vault="Private"`
+    keylist=`op item list --categories SSHKey --format=json --vault="Private" 2>/dev/null`
     if [ "$?" -ne 0 ]; then
       echo "Failed to get retrieve SSH key list"
       return 1
@@ -87,7 +95,7 @@ function openv() {
       _id=$(_val '.id')
 
       local data
-      data=`op item get --format=json "${_id}"`
+      data=`op item get --format=json "${_id}" 2>/dev/null`
       if [ "$?" -ne 0 ]; then
         echo "Failed to get retrieve SSH key"
         return 1
